version: "3.9"

services:
  backend:
    build:
      context: ./battery-mes-backend
    container_name: battery-mes-backend
    ports:
      - "8081:8081"
    environment:
      PYTHON_BASE_URL: http://python-analysis:8000
      JWT_SECRET: ${JWT_SECRET:-battery-mes-secret-key-battery-mes-secret-key-123456}
      DB_USERNAME: ${DB_USERNAME:-scott}
      DB_PASSWORD: ${DB_PASSWORD:-tiger}
    depends_on:
      - python-analysis
      - oracle-db

  frontend:
    build:
      context: ./battery-mes-frontend
    container_name: battery-mes-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  python-analysis:
    build:
      context: ./battery-mes-python
    container_name: battery-mes-python
    ports:
      - "8000:8000"

  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: battery-mes-oracle
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: ${ORACLE_PASSWORD:-oracle}
      APP_USER: ${DB_USERNAME:-scott}
      APP_USER_PASSWORD: ${DB_PASSWORD:-tiger}