apiVersion: v1
kind: Secret
metadata:
  name: battery-mes-secret
  namespace: battery-mes
type: Opaque
stringData:
  JWT_SECRET: "battery-mes-secret-key-battery-mes-secret-key-123456"
  DB_USERNAME: "scott"
  DB_PASSWORD: "tiger"
  ORACLE_PASSWORD: "oracle"
