apiVersion: v1
kind: Secret
metadata:
  name: battery-mes-secret
  namespace: battery-mes
type: Opaque
stringData:
  JWT_SECRET: "여기에_64자_이상_랜덤_문자열_입력"
  DB_USERNAME: "여기에_DB_사용자명_입력"
  DB_PASSWORD: "여기에_강력한_비밀번호_입력"
